/**
 * The governance compiler.
 *
 * Reads governance/rules.ts and emits every other representation of a rule.
 * Generated files carry a header and are checked for drift in CI (`--check`).
 *
 * This is the structural answer to "documentation cannot prevent drift".
 * There is exactly one place a rule is written. Everything else is compiled.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { RULES } from "./rules.js";
import { NO_SLOT_PATTERNS, DESTRUCTIVE, TOP_LEVEL } from "./grammar.js";
import { isCi } from "./types.js";

const ROOT = process.cwd();
const HDR = (src: string) =>
  `<!-- GENERATED by governance/compile.ts from ${src}. DO NOT EDIT. Run \`npm run governance:compile\`. -->`;
const HDR_JS = (src: string) =>
  `// GENERATED by governance/compile.ts from ${src}. DO NOT EDIT. Run \`npm run governance:compile\`.`;

type Out = { path: string; content: string };

function enforcementTable(): string {
  const rows = RULES.map(
    (r) => `| ${r.id} | ${r.statement} | ${r.section} | ${r.class} | ${r.scope} |`
  ).join("\n");
  const ci = RULES.filter(isCi).length;
  const review = RULES.filter((r) => r.class === "REVIEW").length;
  return [
    HDR("governance/rules.ts"),
    "",
    "## Enforcement Register",
    "",
    "A rule not listed here does not exist. This table is compiled from `governance/rules.ts`;",
    "editing it by hand will fail the drift check.",
    "",
    `**${RULES.length} rules — ${ci} CI, ${RULES.length - ci - review} GATE, ${review} REVIEW.**`,
    "",
    "| ID | Rule | § | Class | Scope |",
    "|---|---|---|---|---|",
    rows,
    "",
    "### Cited defects",
    "",
    "Every rule names the defect that justifies it. No defect, no rule.",
    "",
    "| ID | Defect |",
    "|---|---|",
    ...RULES.map((r) => `| ${r.id} | ${r.defect} |`),
    "",
  ].join("\n");
}

function prTemplate(): string {
  const ci = RULES.filter(isCi);
  return [
    "<!-- The PR is the change record. There is no tasks.md / receipt / checklist file. -->",
    HDR("governance/rules.ts"),
    "",
    "`Conformance: Lean ? | Efficient ? | Effective ? — <justification, or the trade made>`",
    "",
    "<!-- Required [R00]. Empty = blocked merge. -->",
    "",
    "---",
    "",
    "**Class:** direct | planned | gated · **Compatibility:** patch | minor | major",
    "",
    "**Origin:** core | product:<name> · **Type:** correction | proposal",
    "",
    "**Problem:**",
    "",
    "**Acceptance condition:**",
    "",
    "## Evidence",
    "",
    "- [ ] Red observed for the intended reason — `<cmd>`",
    "- [ ] Green — `<cmd>`",
    "- [ ] Hosted CI green on this commit, checks dispatched > 0 — `<link>` [R05]",
    "",
    "## Machine-checked for you",
    "",
    `These ${ci.length} rules are enforced by \`npm run verify\`. You do not need to confirm them.`,
    "If CI is green, they hold. If you are tempted to tick them by hand, that is the defect.",
    "",
    ...ci.map((r) => `- \`${r.id}\` ${r.statement}`),
    "",
    "## Rollback",
    "",
    "## Deviations",
    "",
    "<!-- none, or a record with an expiry -->",
    "",
  ].join("\n");
}

function guardDestructive(): string {
  return [
    "#!/usr/bin/env node",
    HDR_JS("governance/grammar.ts"),
    "// PreToolUse:Bash. Supplementary — the control is CI. Fails OPEN on parse error.",
    'import { readFileSync } from "node:fs";',
    "",
    "const DENY = [",
    ...DESTRUCTIVE.map(([re, label]) => `  [${re.toString()}, ${JSON.stringify(label)}],`),
    "];",
    "",
    'let cmd = "";',
    "try {",
    '  const e = JSON.parse(readFileSync(0, "utf8"));',
    '  cmd = e?.tool_input?.command ?? e?.command ?? "";',
    '  if (Array.isArray(cmd)) cmd = cmd.join(" ");',
    "} catch { process.exit(0); }",
    "",
    "for (const [re, label] of DENY) {",
    "  if (re.test(cmd)) {",
    "    console.error(`BLOCKED [guard-destructive]: ${label}\\n  ${cmd}\\n  Ask the operator. Do not work around this.`);",
    "    process.exit(2);",
    "  }",
    "}",
    "process.exit(0);",
    "",
  ].join("\n");
}

function guardGrammar(): string {
  return [
    "#!/usr/bin/env node",
    HDR_JS("governance/grammar.ts"),
    "// PreToolUse:Write|apply_patch. Refuses artifacts with no slot [R24, R18, R10, B1].",
    'import { readFileSync } from "node:fs";',
    "",
    "const NO_SLOT = [",
    ...NO_SLOT_PATTERNS.map((re) => `  ${re.toString()},`),
    "];",
    `const TOP = new Set(${JSON.stringify([...TOP_LEVEL].sort())});`,
    "const SHELL = /\\.(ps1|psm1|psd1|sh|bat|cmd)$/i;",
    "",
    "function block(m) { console.error(`BLOCKED [guard-grammar]\\n  ${m}`); process.exit(2); }",
    "",
    'let p = "";',
    "try {",
    '  const e = JSON.parse(readFileSync(0, "utf8"));',
    '  p = e?.tool_input?.path ?? e?.tool_input?.file_path ?? e?.path ?? "";',
    "} catch { process.exit(0); }",
    "if (!p) process.exit(0);",
    "",
    'const rel = p.replace(/\\\\/g, "/").replace(/^\\.\\//, "");',
    'const seg = rel.split("/");',
    "",
    'if (NO_SLOT.some((re) => re.test(rel))) block(`"${rel}" has no slot in the grammar. [R18] The change record is the PR.`);',
    'if (SHELL.test(rel)) block(`"${rel}" is a shell script. [R10] Write it in TypeScript.`);',
    'if (!TOP.has(seg[0])) block(`"${seg[0]}" is not a legal top-level entry. [R24] Amend the grammar first, in its own PR.`);',
    'if (seg[0] === "capabilities" && seg.length > 1 && seg[1] !== ".gitkeep")',
    '  block("capabilities/ stays empty until two products prove the need. [B1]");',
    "",
    "process.exit(0);",
    "",
  ].join("\n");
}

const OUTPUTS: Out[] = [
  { path: "docs/operating-model/enforcement-register.md", content: enforcementTable() },
  { path: ".github/pull_request_template.md", content: prTemplate() },
  { path: ".codex/hooks/guard-destructive.mjs", content: guardDestructive() },
  { path: ".codex/hooks/guard-grammar.mjs", content: guardGrammar() },
];

const check = process.argv.includes("--check");
let drift = 0;

for (const o of OUTPUTS) {
  const abs = join(ROOT, o.path);
  const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (check) {
    if (current !== o.content) {
      drift++;
      console.error(
        current === null
          ? `  ✗ MISSING generated file: ${o.path}`
          : `  ✗ DRIFT: ${o.path} was hand-edited or the registry changed without recompiling.`
      );
    }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, o.content);
    console.log(`  ✓ ${o.path}`);
  }
}

if (check) {
  if (drift) {
    console.error(
      `\n${drift} generated file(s) out of sync with governance/rules.ts.\n` +
        `Run: npm run governance:compile\n\n` +
        `This is the drift gate. A hand-edited copy of a rule cannot survive a merge —\n` +
        `which is the entire reason the registry exists.`
    );
    process.exit(1);
  }
  console.log("  ✓ no drift — every generated artefact matches the registry");
} else {
  console.log(`\nCompiled ${OUTPUTS.length} artefacts from ${RULES.length} rules.`);
}
