#!/usr/bin/env node
// GENERATED by governance/compile.ts from governance/grammar.ts. DO NOT EDIT. Run `npm run governance:compile`.
// PreToolUse:Write|apply_patch. Refuses artifacts with no slot [R24, R18, R10, B1].
import { readFileSync } from "node:fs";

const NO_SLOT = [
  /(^|\/)tasks\.md$/i,
  /(^|\/)workflow-receipts?\.md$/i,
  /(^|\/)checklist\.md$/i,
  /(^|\/)convergence\.md$/i,
  /(^|\/)(plans|audit|closeout|worker-reports)\//i,
  /(^|\/)\.superpowers\//i,
  /(^|\/)projects\//i,
];
const TOP = new Set([".agents",".codex",".git",".gitattributes",".github",".gitignore",".nvmrc","AGENTS.md","LICENSE","README.md","SECURITY.md","VERIFY-BEFORE-USE.md","VERSION","app-dev.manifest.json","archetypes","capabilities","core","docs","eslint.config.js","governance","node_modules","package-lock.json","package.json","schemas","scripts","standards","tests","tsconfig.json"]);
const SHELL = /\.(ps1|psm1|psd1|sh|bat|cmd)$/i;

function block(m) { console.error(`BLOCKED [guard-grammar]\n  ${m}`); process.exit(2); }

let p = "";
try {
  const e = JSON.parse(readFileSync(0, "utf8"));
  p = e?.tool_input?.path ?? e?.tool_input?.file_path ?? e?.path ?? "";
} catch { process.exit(0); }
if (!p) process.exit(0);

const rel = p.replace(/\\/g, "/").replace(/^\.\//, "");
const seg = rel.split("/");

if (NO_SLOT.some((re) => re.test(rel))) block(`"${rel}" has no slot in the grammar. [R18] The change record is the PR.`);
if (SHELL.test(rel)) block(`"${rel}" is a shell script. [R10] Write it in TypeScript.`);
if (!TOP.has(seg[0])) block(`"${seg[0]}" is not a legal top-level entry. [R24] Amend the grammar first, in its own PR.`);
if (seg[0] === "capabilities" && seg.length > 1 && seg[1] !== ".gitkeep")
  block("capabilities/ stays empty until two products prove the need. [B1]");

process.exit(0);
